apiVersion: v2
appVersion: "1.0.0"
description: A Helm chart for Kubernetes
name: pc-deploy
version: "1.0.0"
dependencies:
  - name: daskhub
    # NOTE: Update dependencies/requirements.txt at the same time.
    # The chart at https://helm.dask.org/ is helpful.
    version: "2021.6.1"
    repository: https://helm.dask.org
  - name: kbatch-proxy
    version: "0.2.5"
    repository: https://kbatch-dev.github.io/kbatch
