#!/usr/bin/env bash
set -eu

echo "[init terraform]"
terraform -chdir=terraform/${ENVIRONMENT} init

echo "[planning terraform]"
terraform -chdir=terraform/${ENVIRONMENT} plan -out plan.tfstate
terraform -chdir=terraform/${ENVIRONMENT} apply plan.tfstate

RESOURCE_GROUP=$(terraform -chdir=terraform/${ENVIRONMENT} output -json resources | jq -r .resource_group)
CLUSTER_NAME=$(terraform -chdir=terraform/${ENVIRONMENT} output -json resources | jq -r .cluster_name)

echo "[getting AKS credentials]"
az aks get-credentials \
    --resource-group "${RESOURCE_GROUP}" \
    --name "${CLUSTER_NAME}" \
    --subscription "Planetary Computer"

echo "[test deployment]"
./tests/run.sh
