#!/usr/bin/env bash
set -eu

cd helm/chart && \
    helm dependency update && \
    cd ../..

cd helm/chart.2 && \
    helm dependency update && \
    cd ../..

echo "[init terraform]"
terraform -chdir=terraform/${ENVIRONMENT} init

echo "[applying terraform]"
terraform -chdir=terraform/${ENVIRONMENT} plan -out plan.tfstate
terraform -chdir=terraform/${ENVIRONMENT} apply plan.tfstate

echo "[getting kubeconfig]"
terraform -chdir=terraform/${ENVIRONMENT} output -json resources | jq -r .kubeconfig > .kubeconfig
export KUBECONFIG=".kubeconfig"

echo "[test deployment]"
./tests/run.sh
