# helper pod for debugging
# Fill in the pvc name below and apply it.
# Then kubectl exec to debug
# kubectl -n prod apply -f scripts/pod.yaml
# kubectl -n prod exec pv-checker -- df -h /mnt/azure
# kubectl -n prod delete pod pv-checker
apiVersion: v1
kind: Pod
metadata:
  name: pv-checker
  namespace: prod
spec:
  restartPolicy: Never
  containers:
  - name: pv-checker
    image: "k8s.gcr.io/busybox"
    command: ["/bin/sh", "-c", "sleep 10000"]
    volumeMounts:
    - name: volume
      mountPath: /mnt/azure
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: claim-
