#!/usr/bin/env bash
echo "[jq]"
sudo apt-get update
sudo apt-get install -y jq

echo "[terraform]"
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt install terraform

echo "[helm]"
wget --quiet https://get.helm.sh/helm-v3.4.1-linux-amd64.tar.gz
tar -zxf helm-v3.4.1-linux-amd64.tar.gz
sudo mv linux-amd64/helm /usr/bin/helm

echo "[kubectl]"
curl -LO "https://storage.googleapis.com/kubernetes-release/release/v0.19.7/bin/linux/amd64/kubectl"
chmod +x kubectl
sudo mv kubectl /usr/bin/kubectl